2023/11/02 04:21:24 failed to dial tcp connection, retrying
2023/11/02 04:21:25 failed to dial tcp connection, retrying
[2023-11-02T04:21:25.758Z] info  code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3
[2023-11-02T04:21:25.759Z] info  Using user-data-dir ~/.local/share/code-server
[2023-11-02T04:21:25.774Z] info  Using config file ~/.config/code-server/config.yaml
[2023-11-02T04:21:25.774Z] info  HTTP server listening on http://127.0.0.1:8080/
[2023-11-02T04:21:25.774Z] info    - Authentication is disabled
[2023-11-02T04:21:25.774Z] info    - Not serving HTTPS
====================================>token: f0ab9ad0-cd85-4405-ba28-2ceaed099b8e
[04:21:28] 




[04:21:28] Extension host agent started.
[04:21:30] [127.0.0.1][123531c0][ManagementConnection] New connection established.
[04:21:30] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[04:21:31] [127.0.0.1][2d0392a7][ExtensionHostConnection] New connection established.
[04:21:31] [127.0.0.1][2d0392a7][ExtensionHostConnection] <380> Launched Extension Host Process.
[2023-11-02T04:23:40.987Z] error Failed to get latest version [38;2;140;140;140m{"error":"connect ETIMEDOUT 20.205.243.168:443"}[0m
[04:23:59] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /opt/conda/lib/python3.8)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8986f1]

goroutine 488 [running]:
http_reverse_proxy/client.sendHttpRequestAndReplyHttpResponse(0xc000014098?, 0x0?, 0xc000292120, 0xc00012a780)
	/builds/hitminer/http_reverse_proxy/client/http_client.go:51 +0xb1
created by http_reverse_proxy/client.startHttpClient
	/builds/hitminer/http_reverse_proxy/client/http_client.go:34 +0x1ea
