2023/12/03 02:15:37 failed to dial tcp connection, retrying
[2023-12-03T02:15:38.256Z] info  code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3
[2023-12-03T02:15:38.257Z] info  Using user-data-dir ~/.local/share/code-server
[2023-12-03T02:15:38.270Z] info  Using config file ~/.config/code-server/config.yaml
[2023-12-03T02:15:38.270Z] info  HTTP server listening on http://127.0.0.1:8080/
[2023-12-03T02:15:38.270Z] info    - Authentication is disabled
[2023-12-03T02:15:38.270Z] info    - Not serving HTTPS
====================================>token: 2830d785-42e9-4bbf-bb63-7d3da27d4898
[02:15:40] 




[02:15:40] Extension host agent started.
[02:15:42] [127.0.0.1][254585fe][ManagementConnection] New connection established.
[02:15:43] [127.0.0.1][6dede499][ExtensionHostConnection] New connection established.
[02:15:43] [127.0.0.1][6dede499][ExtensionHostConnection] <379> Launched Extension Host Process.
[02:15:46] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[02:15:57] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /opt/conda/lib/python3.8)
[2023-12-03T02:17:53.077Z] error Failed to get latest version [38;2;140;140;140m{"error":"connect ETIMEDOUT 20.205.243.168:443"}[0m
[03:42:04] [127.0.0.1][254585fe][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[03:42:05] [127.0.0.1][6dede499][ExtensionHostConnection] <379> Extension Host Process exited with code: 0, signal: null.
2023/12/03 03:52:06 exit program after timeout
