2023/11/26 08:32:33 failed to dial tcp connection, retrying
2023/11/26 08:32:34 failed to dial tcp connection, retrying
[2023-11-26T08:32:34.866Z] info  code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3
[2023-11-26T08:32:34.867Z] info  Using user-data-dir ~/.local/share/code-server
[2023-11-26T08:32:34.886Z] info  Using config file ~/.config/code-server/config.yaml
[2023-11-26T08:32:34.886Z] info  HTTP server listening on http://127.0.0.1:8080/
[2023-11-26T08:32:34.886Z] info    - Authentication is disabled
[2023-11-26T08:32:34.886Z] info    - Not serving HTTPS
====================================>token: eee5459c-88d1-48f5-973d-3c8eb0cb1cb1
[08:32:37] 




[08:32:37] Extension host agent started.
[08:32:40] [127.0.0.1][e305d9b9][ManagementConnection] New connection established.
[08:32:41] [127.0.0.1][97bf82ab][ExtensionHostConnection] New connection established.
[08:32:41] [127.0.0.1][97bf82ab][ExtensionHostConnection] <381> Launched Extension Host Process.
[08:32:44] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[08:32:55] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /opt/conda/lib/python3.8)
[2023-11-26T08:34:50.166Z] error Failed to get latest version [38;2;140;140;140m{"error":"connect ETIMEDOUT 20.205.243.168:443"}[0m
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8986f1]

goroutine 240 [running]:
http_reverse_proxy/client.sendHttpRequestAndReplyHttpResponse(0xc0003eb660?, 0xc0003eb7d0?, 0xc00039a000, 0xc000296060)
	/builds/hitminer/http_reverse_proxy/client/http_client.go:51 +0xb1
created by http_reverse_proxy/client.startHttpClient
	/builds/hitminer/http_reverse_proxy/client/http_client.go:34 +0x1ea
