2023/11/02 08:23:55 failed to dial tcp connection, retrying
[2023-11-02T08:23:56.776Z] info  code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3
[2023-11-02T08:23:56.778Z] info  Using user-data-dir ~/.local/share/code-server
[2023-11-02T08:23:56.791Z] info  Using config file ~/.config/code-server/config.yaml
[2023-11-02T08:23:56.791Z] info  HTTP server listening on http://127.0.0.1:8080/
[2023-11-02T08:23:56.791Z] info    - Authentication is disabled
[2023-11-02T08:23:56.791Z] info    - Not serving HTTPS
====================================>token: 9172737d-f74a-4974-99bf-40792c3a0f0d
[08:23:59] 




[08:23:59] Extension host agent started.
[08:24:00] [127.0.0.1][c3ca1b39][ManagementConnection] New connection established.
[08:24:01] [127.0.0.1][bfb02368][ExtensionHostConnection] New connection established.
[08:24:01] [127.0.0.1][bfb02368][ExtensionHostConnection] <378> Launched Extension Host Process.
[08:24:04] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[08:24:15] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /opt/conda/lib/python3.8)
[2023-11-02T08:26:12.022Z] error Failed to get latest version [38;2;140;140;140m{"error":"connect ETIMEDOUT 20.205.243.168:443"}[0m
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8986f1]

goroutine 381 [running]:
http_reverse_proxy/client.sendHttpRequestAndReplyHttpResponse(0x0?, 0x0?, 0xc0000d0000, 0xc00012a780)
	/builds/hitminer/http_reverse_proxy/client/http_client.go:51 +0xb1
created by http_reverse_proxy/client.startHttpClient
	/builds/hitminer/http_reverse_proxy/client/http_client.go:34 +0x1ea
