2023/11/28 06:19:54 failed to dial tcp connection, retrying
2023/11/28 06:19:55 failed to dial tcp connection, retrying
[2023-11-28T06:19:55.114Z] info  code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3
[2023-11-28T06:19:55.115Z] info  Using user-data-dir ~/.local/share/code-server
[2023-11-28T06:19:55.130Z] info  Using config file ~/.config/code-server/config.yaml
[2023-11-28T06:19:55.130Z] info  HTTP server listening on http://127.0.0.1:8080/
[2023-11-28T06:19:55.130Z] info    - Authentication is disabled
[2023-11-28T06:19:55.131Z] info    - Not serving HTTPS
====================================>token: 1f322037-f787-4712-b16f-861a91f131d6
[06:19:57] 




[06:19:57] Extension host agent started.
[06:19:59] [127.0.0.1][2628a820][ManagementConnection] New connection established.
[06:20:00] [127.0.0.1][d379bb69][ExtensionHostConnection] New connection established.
[06:20:00] [127.0.0.1][d379bb69][ExtensionHostConnection] <380> Launched Extension Host Process.
[06:20:03] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[06:20:13] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /opt/conda/lib/python3.8)
[2023-11-28T06:22:09.591Z] error Failed to get latest version [38;2;140;140;140m{"error":"connect ETIMEDOUT 20.205.243.168:443"}[0m
[08:34:56] [127.0.0.1][2628a820][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[08:34:56] [127.0.0.1][d379bb69][ExtensionHostConnection] <380> Extension Host Process exited with code: 0, signal: null.
2023/11/28 08:44:58 exit program after timeout
