2023/12/12 01:12:33 failed to dial tcp connection, retrying
[2023-12-12T01:12:34.006Z] info  code-server 4.11.0 85e083580dec27ef19827ff42d3c9257d56ea7e3
[2023-12-12T01:12:34.007Z] info  Using user-data-dir ~/.local/share/code-server
[2023-12-12T01:12:34.028Z] info  Using config file ~/.config/code-server/config.yaml
[2023-12-12T01:12:34.028Z] info  HTTP server listening on http://127.0.0.1:8080/
====================================>token: a198bc06-add2-4fbd-8cb6-4b151e38c58a
[2023-12-12T01:12:34.029Z] info    - Authentication is disabled
[2023-12-12T01:12:34.029Z] info    - Not serving HTTPS
[01:12:35] 




[01:12:35] Extension host agent started.
[01:12:37] [127.0.0.1][6acd6088][ManagementConnection] New connection established.
[01:12:38] [127.0.0.1][1ce98ff6][ExtensionHostConnection] New connection established.
[01:12:38] [127.0.0.1][1ce98ff6][ExtensionHostConnection] <380> Launched Extension Host Process.
[01:12:42] Using the in-memory credential store as the operating system's credential store could not be accessed. Please see https://aka.ms/vscode-server-keyring on how to set this up. Details: libsecret-1.so.0: cannot open shared object file: No such file or directory
[01:12:55] [File Watcher (parcel)] Inotify limit reached (ENOSPC) (path: /opt/conda/lib/python3.8)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8986f1]

goroutine 274 [running]:
http_reverse_proxy/client.sendHttpRequestAndReplyHttpResponse(0xc000573e60?, 0xc000573fd0?, 0xc000292000, 0xc00012a780)
	/builds/hitminer/http_reverse_proxy/client/http_client.go:51 +0xb1
created by http_reverse_proxy/client.startHttpClient
	/builds/hitminer/http_reverse_proxy/client/http_client.go:34 +0x1ea
